# Generated by Django 4.2 on 2023-04-16 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='provider',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='basis.company'),
        ),
    ]
